### ISSUE TITLE
Don't block `--dry-run` (`-d`) updates

### ISSUE THREAD

**Issue by Callek** [travishathaway/conda-envlock#2]
When I have an environment protected, I still sometimes want to see what is out of date and can be updated.

In such a case I usually run `conda update --all --dry-run` which since its not actually changing the environment would be useful to see that supported.

**Comment by travishathaway** [comment]
@Callek,

I agree that this would be a good idea, and it should be fairly simple to implement.

We could add this as a milestone for the next release.
