### ISSUE TITLE
Move to `conda-incubator`?

### ISSUE THREAD

**Issue by jaimergp** [travishathaway/conda-envlock#5]
I really like this project. It's a commonly asked feature that should be part of some opinionated book of conda best practices, and I think it would benefit from having more visibility.

WDYT @travishathaway?

**Comment by travishathaway** [comment]
@jaimergp,

Yes, that sounds like a good idea. Let's move it to conda-incubator. I'm assuming you'll be the sponsoring steering council member?

**Comment by jaimergp** [comment]
Yep, I'll create the governance issue and start the process. Thanks!

**Comment by jaimergp** [comment]
See https://github.com/conda/governance/issues/138.
