### ISSUE TITLE
IMHO: conda plist should be "conda protect list"

### ISSUE THREAD

**Issue by bkreider** [travishathaway/conda-envlock#6]
I suggest keeping all commands under the "conda protect" namespace to keep the "global" namespace cleaner.

**Comment by travishathaway** [comment]
I agree with this.

**Comment by travishathaway** [comment]
What about `conda protect --list`? Otherwise, this really messes up a lot of stuff with the implementation.

Alternatively we could do `conda protect -n/-p <name/prefix>`, but I kind of like having `conda protect <env>` as a simple invocation.

**Comment by travishathaway** [comment]
@bkreider,

see https://github.com/conda-incubator/conda-protect/pull/11
